[package]
name = "mango-macro"
version = "3.0.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "^1.0.75"
solana-program = "^1.7.10"
bytemuck = "^1.7.2"
quote = "^1.0.9"

mango-common = { path = "../common" }