[package]
name = "mango-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "^1.6.9"
bytemuck = "^1.4.1"
