[package]
name = "merps"
version = "0.0.1"
authors = ["blockworks"]
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
solana-program = "^1.6.4"
arrayref = "^0.3.6"
serde = "^1.0.118"
bytemuck = "^1.4.1"
bincode = "^1.3.1"
fixed = { version = "^1.8.0", features=["serde"] }
fixed-macro = "^1.1.1"
enumflags2 = "^0.6.4"
num_enum = "^0.5.1"
thiserror = "^1.0.24"
spl-token = { version = "^3.0.0", features=["no-entrypoint"] }

serum_dex = { version = "^0.2", git = "https://github.com/blockworks-foundation/serum-dex.git", features=["no-entrypoint", "program"] }

[profile.release]
lto = true

[lib]
name = "merps"
crate-type = ["cdylib", "lib"]
