[package]
name = "merps"
version = "0.0.1"
authors = ["blockworks"]
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
solana-program = "^1.6.4"
arrayref = "^0.3.6"
serde = "^1.0.118"
bytemuck = "^1.4.1"
bincode = "^1.3.1"
fixed = { version = "^1.8.0", features = ["serde"] }
fixed-macro = "^1.1.1"
enumflags2 = "^0.6.4"
num_enum = "^0.5.1"
thiserror = "^1.0.24"
spl-token = { version = "^3.0.0", features = ["no-entrypoint"] }
serum_dex = { version = "^0.2", git = "https://github.com/blockworks-foundation/serum-dex.git", features = ["no-entrypoint", "program"] }
static_assertions = "^1.1.0"
flux-aggregator = { version = "^0.1", git = "https://github.com/blockworks-foundation/solana-flux-aggregator.git", features = ["program", "no-entrypoint"] }

[dev-dependencies]
safe-transmute = "^0.11.0"
solana-sdk = "^1.6.4"
solana-program-test = "^1.6.4"


[profile.release]
lto = true

#[profile.test]
#lto = true
#opt-level = 2

[lib]
name = "merps"
crate-type = ["cdylib", "lib"]
